apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-ready
spec:
  replicas: 3
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.absolute = 1GB
      vm_memory_high_watermark.relative= 1.0
  persistence:
    #storageClassName: fast
    storage: "3Gi"
  override:
    #    service:
    #           annotations:
    #             networking.gke.io/load-balancer-type: "Internal"
    #      type: LoadBalancer
    #      spec:
    #        loadBalancerIp: "Internal"
    statefulSet:
      spec:
        podManagementPolicy: Parallel
        template:
          spec:
            priorityClassName: high-priority
            containers: [ ]